### ISSUE TITLE
How is it possible to do pull requests?

### ISSUE THREAD

**Issue by lannin** [clld/asjp#10]
I would like to ask what I need to do if I would like to add some updates to ASJP and it's easy for me to do it through git-hub, but I cannot find to files with sources.
For instance, I've found that https://asjp.clld.org/sources/2698 is the wrong source to Aneme Wake and Moikodi (I mean these lists, in fact, come from another source than it mentioned ( https://glottolog.org/resource/reference/id/302898 )), what do I need to do for the pull request?

**Comment by chrzyki** [comment]
Heya @lannin,

the raw data, which is then 'translated' into a database by [this script](https://github.com/clld/asjp/blob/master/asjp/scripts/initializedb.py), can be found in [this](https://github.com/clld/asjp-data) repository, meaning that pull requests would have to be made there with updating the necessary files. For your example, I suggest checking:

- https://github.com/clld/asjp-data/blob/master/sources_listss17.xlsx
- https://github.com/clld/asjp-data/blob/master/sources_listss18.xlsx
- potentially everything in https://github.com/clld/asjp-data/tree/master/sources as well

If more updates and PRs are planned, I suggest we think about an easier workflow than editing the raw tables (potentially with some input by @xrotwang).

**Comment by xrotwang** [comment]
@lannin thanks for bringing this to our attention! As @chrzyki explained, currently, the ASJP data isn't really curated collaboratively, so it isn't really set-up for accepting pull requests. I will talk to Sören Wichemann about which direction he wants the project to go in!
