### ISSUE TITLE
Maximum number of rows and columns using asjp62.exe

### ISSUE THREAD

**Issue by py5gol** [clld/asjp#5]
Dear all

I am running asjp62.exe with an input file containing around 600 languages. 
The result file only includes 32 languages. I changed the file to exclude any filter on time but the result keeps coming with just 32 languages. 
Is there any config that I might be missing?

Best wishes,
Roberto

**Comment by xrotwang** [comment]
If you could send your input file to the address given at http://asjp.clld.org/contact we could have a look.

**Comment by py5gol** [comment]
Sorry about the long time to respond. It was my mistake when mergings a series of asjp files.

**Comment by xrotwang** [comment]
Ok. Thanks for getting back!
